name: Release Mas Python Services
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
jobs:
  release-please:
    uses: dakispro/.github/.github/workflows/release.yml@main
    with:
      push_docker: false
  pypi-publish:
    needs: release-please
    if: ${{ needs['release-please'].outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/zalfmas-common
    steps:
      # Build + publish Python package to PyPI on release via Trusted Publishing
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build Python distribution
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
