[service]
id = "1adc6c19-3801-4da9-8a76-ff682e8eebd9"
name = "SQLite Soil Data Service"
description = "Serve soil profiles from an ascii grid given some lat/lon coordinate."
path_to_sqlite_db = "path to sqlite db"
path_to_ascii_soil_grid = "path_to_ascii_grid"
#grid_crs = "utm21n" # latlon | wgs84 | gk3 | gk4 | gk5 | utm21s | utm32n
epsg_code = 25832
#fixed_sturdy_ref_token = "soil"
# sturdy ref to a container which is used by the service to store it's data/state etc.
#storage_container_sr = "capnp://the_host_key@host:port/a_sturdy_ref_token"

# at which registries the current service should be registered, might be only one
#[[service.registries]]
#name = "SQLite Soil Data Service"
#category_id = "soils"
# sturdy ref to a registry where the service should be registered at
#sturdy_ref = "capnp://the_host_key@host:port/a_sturdy_ref_token"

[vat]
#host = "localhost"
#port = "9999"
serve_bootstrap = true
# sturdy ref to container used for the restorer serving the vat
#restorer_container_sr = "sturdy ref"

# at which resolvers should the vat be registered under the current vat id and optional alias
#[[vat.resolvers]]
#sturdy_ref = "sturdy ref"
#alias = "soil"
