[service]
id = "225282df-abe1-4029-b093-ef7bd4f82ff1"
name = "ASCII Grid Service"
description = "Serve values of an ascii grid."
path_to_ascii_grid = "path_to_ascii_grid"
#grid_crs = "utm21n" # latlon | wgs84 | gk3 | gk4 | gk5 | utm21s | utm32n
epsg_code = 25832
val_type = "float" # "int" | "float"
#fixed_sturdy_ref_token = "ascii_grid"
# sturdy ref to a container which is used by the service to store it's data/state etc.
#storage_container_sr = "capnp://the_host_key@host:port/a_sturdy_ref_token"

# at which registries the current service should be registered, might be only one
#[[service.registries]]
#name = "ASCII Grid Service"
#category_id = "grids"
# sturdy ref to a registry where the service should be registered at
#sturdy_ref = "capnp://the_host_key@host:port/a_sturdy_ref_token"

[vat]
#host = "localhost"
#port = "9999"
serve_bootstrap = true
# sturdy ref to container used for the restorer serving the vat
#restorer_container_sr = "sturdy ref"

# at which resolvers should the vat be registered under the current vat id and optional alias
#[[vat.resolvers]]
#sturdy_ref = "sturdy ref"
#alias = "ascii_grid_service"
