[service]
id = "1cc8e558-ef15-4adf-a7ee-3a9ae34de5f2"
name = "BÜK1000 Soil Data Service"
description = "Serve soil profiles from the BÜK1000 german soil map."
path_to_sqlite_db = "/home/berg/GitHub/mas-infrastructure/data/soil/buek1000.sqlite"
path_to_ascii_soil_grid = "/home/berg/GitHub/mas-infrastructure/data/soil/buek1000_1000_31469_gk5.asc"
#grid_crs = "gk5" # latlon | wgs84 | gk3 | gk4 | gk5 | utm21s | utm32n
epsg_code = 31469
#fixed_sturdy_ref_token = "buek1000"
# sturdy ref to a container which is used by the service to store it's data/state etc.
#storage_container_sr = "capnp://the_host_key@host:port/a_sturdy_ref_token"

# at which registries the current service should be registered, might be only one
#[[service.registries]]
#name = "SQLite Soil Data Service"
#category_id = "soils"
# sturdy ref to a registry where the service should be registered at
#sturdy_ref = "capnp://the_host_key@host:port/a_sturdy_ref_token"

[vat]
#host = "localhost"
#port = "9999"
serve_bootstrap = true
# sturdy ref to container used for the restorer serving the vat
#restorer_container_sr = "sturdy ref"

# at which resolvers should the vat be registered under the current vat id and optional alias
#[[vat.resolvers]]
#sturdy_ref = "sturdy ref"
#alias = "buek1000"
