[service]
id = "559c500a-12f9-4b4b-8019-011ad9f16f11"
name = "DEM 1000m resolution Grid Service"
description = "Serve values of an ascii grid."
path_to_ascii_grid = "/home/berg/GitHub/mas-infrastructure/data/geo/dem_1000_31469_gk5.asc"
#grid_crs = "gk5" # latlon | wgs84 | gk3 | gk4 | gk5 | utm21s | utm32n
epsg_code = 31469
val_type = "float" # "int" | "float"
#fixed_sturdy_ref_token = "ascii_grid"
# sturdy ref to a container which is used by the service to store it's data/state etc.
#storage_container_sr = "capnp://the_host_key@host:port/a_sturdy_ref_token"

# at which registries the current service should be registered, might be only one
#[[service.registries]]
#name = "ASCII Grid Service"
#category_id = "grids"
# sturdy ref to a registry where the service should be registered at
#sturdy_ref = "capnp://the_host_key@host:port/a_sturdy_ref_token"

[vat]
#host = "localhost"
#port = "9999"
serve_bootstrap = true
# sturdy ref to container used for the restorer serving the vat
#restorer_container_sr = "sturdy ref"

# at which resolvers should the vat be registered under the current vat id and optional alias
#[[vat.resolvers]]
#sturdy_ref = "sturdy ref"
#alias = "ascii_grid_service"
