# which services this vat will serve, might often be just one
[service]
id = "cbbcfa21-3ff2-4e92-b366-bcfc7fe05ead"
name = "DWD/UBN - historical - 1901 - 2023"
description = "Serves the DWD climate data regionalized by University of Bonn (Andreas Enders)."
path_to_data = "/run/user/1000/gvfs/sftp:host=login01.cluster.zalf.de,user=rpm/beegfs/common/data/climate/dwd/csvs/germany_ubn_1951-01-01_to_2024-08-30"
path_to_latlon_to_rowcol = "/run/user/1000/gvfs/sftp:host=login01.cluster.zalf.de,user=rpm/beegfs/common/data/climate/dwd/csvs/latlon-to-rowcol.json"
#fixed_sturdy_ref_token = "dwd_climate_data_bonn"
# sturdy ref to a container which is used by the service to store it's data/state etc.
#storage_container_sr = "capnp://the_host_key@host:port/a_sturdy_ref_token"

# at which registries the current service should be registered, might be only one
[[service.registries]]
#name = "DWD/UBN - historical data - 1951-2023"
#category_id = "climate"
# sturdy ref to a registry where the service should be registered at
#sturdy_ref = "capnp://the_host_key@host:port/a_sturdy_ref_token"

[vat]
#host = "localhost"
port = "9999"
serve_bootstrap = true
# sturdy ref to container used for the restorer serving the vat
restorer_container_sr = "capnp://UsDvHic7pWXb5R7e1HTFwNB5kKhqZEflZp9_Srbjq4Q=@10.10.28.186:45195/203d7af8-6246-4657-9c9d-63ba64248322"

# at which resolvers should the vat be registered under the current vat id and optional alias
[[vat.resolvers]]
sturdy_ref = "capnp://OLBqQD7KRvJJFgAoXrcUlt5i7rb_pjyNE9ZB7v8Shew@10.10.28.186:36425/81707b08-08c5-4872-be70-a227e5115940"
alias = "dwd_climate_data_bonn"
